<!--
/**
 * Store Locator
 * Templates for displaying content on Contact Us page
 *
 * @category  Internship
 * @package   Internship\StoreLocator
 * @author    Andrii Tomkiv <tomkivandrii18@gmail.com>
 * @copyright 2022 Elogic
 */
-->

<?php
/**
 * @var Internship\StoreLocator\Block\Data $block
 */
?>
<?php if(!empty($block->getCollection())) : ?>
    <table>
        <tr>
            <th>Image</th>
            <th>Name</th>
            <th>Description</th>
            <th>Opening Time</th>
            <th>Closing Time</th>
            <th>Latitude</th>
            <th>Longitude</th>
        </tr>
        <?php foreach ($block->getCollection() as $key => $item) : ?>
            <tr>
                <td>
                    <?php $imagePath = $block->getFilePath($item->getPath());
                    echo "<img src ='$imagePath' />"; ?>
                </td>
                <td><?= $item->getName() ?></td>
                <td><?= $item->getDescription() ?></td>
                <td><?= $item->getOpenTime() ?></td>
                <td><?= $item->getCloseTime() ?></td>
                <td><?= $item->getLatitude() ?></td>
                <td><?= $item->getLongitude() ?></td>
            </tr>
        <?php endforeach; ?>
    </table>
<?php endif ?>
